package com.yhh.whbx.card.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.yhh.whbx.core.CoreModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCardsCarPh<M extends BaseCardsCarPh<M>> extends CoreModel<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}

	public java.lang.String getType() {
		return getStr("type");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return getStr("name");
	}

	public void setCertTypeId(java.lang.Integer certTypeId) {
		set("certTypeId", certTypeId);
	}

	public java.lang.Integer getCertTypeId() {
		return getInt("certTypeId");
	}

	public void setCertCode(java.lang.String certCode) {
		set("certCode", certCode);
	}

	public java.lang.String getCertCode() {
		return getStr("certCode");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}

	public java.lang.String getAddress() {
		return getStr("address");
	}

	public void setCardsId(java.lang.Integer cardsId) {
		set("cardsId", cardsId);
	}

	public java.lang.Integer getCardsId() {
		return getInt("cardsId");
	}

	public void setCAt(java.util.Date cAt) {
		set("cAt", cAt);
	}

	public java.util.Date getCAt() {
		return get("cAt");
	}

	public void setLinkName(java.lang.String linkName) {
		set("linkName", linkName);
	}

	public java.lang.String getLinkName() {
		return getStr("linkName");
	}

	public void setEmail(java.lang.String email) {
		set("email", email);
	}

	public java.lang.String getEmail() {
		return getStr("email");
	}

	public void setTel(java.lang.String tel) {
		set("tel", tel);
	}

	public java.lang.String getTel() {
		return getStr("tel");
	}

}
