package com.yhh.whbx.card.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseInsuranceOcc<M extends BaseInsuranceOcc<M>> extends Model<M> implements IBean {

	public void setType(String type) {
		set("type", type);
	}

	public String getType() {
		return getStr("type");
	}

	public void setPCode(String pCode) {
		set("pCode", pCode);
	}

	public String getPCode() {
		return getStr("pCode");
	}

	public void setCode(String code) {
		set("code", code);
	}

	public String getCode() {
		return getStr("code");
	}

	public void setName(String name) {
		set("name", name);
	}

	public String getName() {
		return getStr("name");
	}

	public void setInsurance(String insurance) {
		set("insurance", insurance);
	}

	public String getInsurance() {
		return getStr("insurance");
	}

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return getLong("id");
	}

}
