package com.yhh.whbx.card.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;
import com.yhh.whbx.core.CoreModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUnlock<M extends BaseUnlock<M>> extends CoreModel<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return getLong("id");
	}

	public void setDepotId(Integer depotId) {
		set("depotId", depotId);
	}

	public Integer getDepotId() {
		return getInt("depotId");
	}

	public void setBNum(Integer bNum) {
		set("bNum", bNum);
	}

	public Integer getBNum() {
		return getInt("bNum");
	}

	public void setENum(Integer eNum) {
		set("eNum", eNum);
	}

	public Integer getENum() {
		return getInt("eNum");
	}

	public void setOper(Integer oper) {
		set("oper", oper);
	}

	public Integer getOper() {
		return getInt("oper");
	}

	public void setCAt(java.util.Date cAt) {
		set("cAt", cAt);
	}

	public java.util.Date getCAt() {
		return get("cAt");
	}

}
