package com.yhh.whbx.card.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;
import com.yhh.whbx.core.CoreModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCardapply<M extends BaseCardapply<M>> extends CoreModel<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return getLong("id");
	}

	public void setCardtypeId(Integer cardtypeId) {
		set("cardtypeId", cardtypeId);
	}

	public Integer getCardtypeId() {
		return getInt("cardtypeId");
	}

	public void setBatch(String batch) {
		set("batch", batch);
	}

	public String getBatch() {
		return getStr("batch");
	}

	public void setMedia(Integer media) {
		set("media", media);
	}

	public Integer getMedia() {
		return getInt("media");
	}

	public void setNum(Integer num) {
		set("num", num);
	}

	public Integer getNum() {
		return getInt("num");
	}

	public void setCheckStatus(String checkStatus) {
		set("checkStatus", checkStatus);
	}

	public String getCheckStatus() {
		return getStr("checkStatus");
	}

	public void setOper(Integer oper) {
		set("oper", oper);
	}

	public Integer getOper() {
		return getInt("oper");
	}

	public void setCAt(java.util.Date cAt) {
		set("cAt", cAt);
	}

	public java.util.Date getCAt() {
		return get("cAt");
	}

	public void setDAt(java.util.Date dAt) {
		set("dAt", dAt);
	}

	public java.util.Date getDAt() {
		return get("dAt");
	}

	public void setDownloadAt(java.util.Date downloadAt) {
		set("downloadAt", downloadAt);
	}

	public java.util.Date getDownloadAt() {
		return get("downloadAt");
	}

	public void setStatus(String status) {
		set("status", status);
	}

	public String getStatus() {
		return getStr("status");
	}

	public void setRemark(String remark) {
		set("remark", remark);
	}

	public String getRemark() {
		return getStr("remark");
	}

	public void setExeCard(String exeCard) {
		set("exeCard", exeCard);
	}

	public String getExeCard() {
		return getStr("exeCard");
	}

	public void setCheckReason(java.lang.String checkReason) {
		set("checkReason", checkReason);
	}

	public java.lang.String getCheckReason() {
		return getStr("checkReason");
	}

	public void setCheckOper(java.lang.Integer checkOper) {
		set("checkOper", checkOper);
	}

	public java.lang.Integer getCheckOper() {
		return getInt("checkOper");
	}

}
