package com.yhh.whbx.card.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.yhh.whbx.core.CoreModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCardsCarIp<M extends BaseCardsCarIp<M>> extends CoreModel<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setProp(java.lang.String prop) {
		set("prop", prop);
	}

	public java.lang.String getProp() {
		return getStr("prop");
	}

	public void setSeatCount(java.lang.String seatCount) {
		set("seatCount", seatCount);
	}

	public java.lang.String getSeatCount() {
		return getStr("seatCount");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	public java.lang.Integer getType() {
		return getInt("type");
	}

	public void setEngineNum(java.lang.String engineNum) {
		set("engineNum", engineNum);
	}

	public java.lang.String getEngineNum() {
		return getStr("engineNum");
	}

	public void setFrameNum(java.lang.String frameNum) {
		set("frameNum", frameNum);
	}

	public java.lang.String getFrameNum() {
		return getStr("frameNum");
	}

	public void setPlateNum(java.lang.String plateNum) {
		set("plateNum", plateNum);
	}

	public java.lang.String getPlateNum() {
		return getStr("plateNum");
	}

	public void setCAt(java.util.Date cAt) {
		set("cAt", cAt);
	}

	public java.util.Date getCAt() {
		return get("cAt");
	}

	public void setCardsId(java.lang.Integer cardsId) {
		set("cardsId", cardsId);
	}

	public java.lang.Integer getCardsId() {
		return getInt("cardsId");
	}

}
