package com.yhh.whbx.card.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;
import com.yhh.whbx.core.CoreModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCardsCarIp<M extends BaseCardsCarIp<M>> extends CoreModel<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return getLong("id");
	}

	public void setProp(String prop) {
		set("prop", prop);
	}

	public String getProp() {
		return getStr("prop");
	}

	public void setSeatCount(String seatCount) {
		set("seatCount", seatCount);
	}

	public String getSeatCount() {
		return getStr("seatCount");
	}

	public void setType(String type) {
		set("type", type);
	}

	public String getType() {
		return getStr("type");
	}

	public void setEngineNum(String engineNum) {
		set("engineNum", engineNum);
	}

	public String getEngineNum() {
		return getStr("engineNum");
	}

	public void setFrameNum(String frameNum) {
		set("frameNum", frameNum);
	}

	public String getFrameNum() {
		return getStr("frameNum");
	}

	public void setPlateNum(String plateNum) {
		set("plateNum", plateNum);
	}

	public String getPlateNum() {
		return getStr("plateNum");
	}

	public void setCAt(java.util.Date cAt) {
		set("cAt", cAt);
	}

	public java.util.Date getCAt() {
		return get("cAt");
	}

	public void setCardsId(Integer cardsId) {
		set("cardsId", cardsId);
	}

	public Integer getCardsId() {
		return getInt("cardsId");
	}

}
