package com.yhh.whbx.card.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.yhh.whbx.core.CoreModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCards<M extends BaseCards<M>> extends CoreModel<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setCode(java.lang.String code) {
		set("code", code);
	}

	public java.lang.String getCode() {
		return getStr("code");
	}

	public void setPwd(java.lang.String pwd) {
		set("pwd", pwd);
	}

	public java.lang.String getPwd() {
		return getStr("pwd");
	}

	public void setAct(java.lang.String act) {
		set("act", act);
	}

	public java.lang.String getAct() {
		return getStr("act");
	}

	public void setActAt(java.util.Date actAt) {
		set("actAt", actAt);
	}

	public java.util.Date getActAt() {
		return get("actAt");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return getStr("status");
	}

	public void setApplyId(java.lang.Integer applyId) {
		set("applyId", applyId);
	}

	public java.lang.Integer getApplyId() {
		return getInt("applyId");
	}

	public void setIsLocked(java.lang.String isLocked) {
		set("isLocked", isLocked);
	}

	public java.lang.String getIsLocked() {
		return getStr("isLocked");
	}

	public void setUnlockId(java.lang.Integer unlockId) {
		set("unlockId", unlockId);
	}

	public java.lang.Integer getUnlockId() {
		return getInt("unlockId");
	}

	public void setDepotId(java.lang.Integer depotId) {
		set("depotId", depotId);
	}

	public java.lang.Integer getDepotId() {
		return getInt("depotId");
	}

	public void setSeq(java.lang.Integer seq) {
		set("seq", seq);
	}

	public java.lang.Integer getSeq() {
		return getInt("seq");
	}

	public void setExportCode(java.lang.String exportCode) {
		set("exportCode", exportCode);
	}

	public java.lang.String getExportCode() {
		return getStr("exportCode");
	}

	public void setPolicyNum(java.lang.String policyNum) {
		set("policyNum", policyNum);
	}

	public java.lang.String getPolicyNum() {
		return getStr("policyNum");
	}

	public void setExportAt(java.util.Date exportAt) {
		set("exportAt", exportAt);
	}

	public java.util.Date getExportAt() {
		return get("exportAt");
	}

	public void setReportTel(java.lang.String reportTel) {
		set("reportTel", reportTel);
	}

	public java.lang.String getReportTel() {
		return getStr("reportTel");
	}

	public void setBAt(String bAt) {
		set("bAt", bAt);
	}

	public String  getBAt() {
		return getStr("bAt");
	}

	public void setEAt(String eAt) {
		set("eAt", eAt);
	}

	public String getEAt() {
		return getStr("eAt");
	}

}
