package com.yhh.whbx.card.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;
import com.yhh.whbx.core.CoreModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCardsPh<M extends BaseCardsPh<M>> extends CoreModel<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return getLong("id");
	}

	public void setCardsId(Integer cardsId) {
		set("cardsId", cardsId);
	}

	public Integer getCardsId() {
		return getInt("cardsId");
	}

	public void setName(String name) {
		set("name", name);
	}

	public String getName() {
		return getStr("name");
	}

	public void setIdCard(String idCard) {
		set("idCard", idCard);
	}

	public String getIdCard() {
		return getStr("idCard");
	}

	public void setSex(String sex) {
		set("sex", sex);
	}

	public String getSex() {
		return getStr("sex");
	}

	public void setBirthDay(java.util.Date birthDay) {
		set("birthDay", birthDay);
	}

	public java.util.Date getBirthDay() {
		return get("birthDay");
	}

	public void setEmail(String email) {
		set("email", email);
	}

	public String getEmail() {
		return getStr("email");
	}

	public void setTel(String tel) {
		set("tel", tel);
	}

	public String getTel() {
		return getStr("tel");
	}

	public void setAddress(String address) {
		set("address", address);
	}

	public String getAddress() {
		return getStr("address");
	}

	public void setCAt(java.util.Date cAt) {
		set("cAt", cAt);
	}

	public java.util.Date getCAt() {
		return get("cAt");
	}

	public void setCertTypeId(Integer certTypeId) {
		set("certTypeId", certTypeId);
	}

	public Integer getCertTypeId() {
		return getInt("certTypeId");
	}

}
