package com.yhh.whbx.card.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;
import com.yhh.whbx.core.CoreModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCardsCarPh<M extends BaseCardsCarPh<M>> extends CoreModel<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return getLong("id");
	}

	public void setType(String type) {
		set("type", type);
	}

	public String getType() {
		return getStr("type");
	}

	public void setName(String name) {
		set("name", name);
	}

	public String getName() {
		return getStr("name");
	}

	public void setCertTypeId(Integer certTypeId) {
		set("certTypeId", certTypeId);
	}

	public Integer getCertTypeId() {
		return getInt("certTypeId");
	}

	public void setCertCode(String certCode) {
		set("certCode", certCode);
	}

	public String getCertCode() {
		return getStr("certCode");
	}

	public void setAddress(String address) {
		set("address", address);
	}

	public String getAddress() {
		return getStr("address");
	}

	public void setCardsId(Integer cardsId) {
		set("cardsId", cardsId);
	}

	public Integer getCardsId() {
		return getInt("cardsId");
	}

	public void setCAt(java.util.Date cAt) {
		set("cAt", cAt);
	}

	public java.util.Date getCAt() {
		return get("cAt");
	}

	public void setLinkName(String linkName) {
		set("linkName", linkName);
	}

	public String getLinkName() {
		return getStr("linkName");
	}

	public void setEmail(String email) {
		set("email", email);
	}

	public String getEmail() {
		return getStr("email");
	}

	public void setTel(String tel) {
		set("tel", tel);
	}

	public String getTel() {
		return getStr("tel");
	}

}
