package com.yhh.whbx.card.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;
import com.yhh.whbx.core.CoreModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCardsIp<M extends BaseCardsIp<M>> extends CoreModel<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return getLong("id");
	}

	public void setRelationship(String relationship) {
		set("relationship", relationship);
	}

	public String getRelationship() {
		return getStr("relationship");
	}

	public void setName(Integer name) {
		set("name", name);
	}

	public Integer getName() {
		return getInt("name");
	}

	public void setCertTypeId(Integer certTypeId) {
		set("certTypeId", certTypeId);
	}

	public Integer getCertTypeId() {
		return getInt("certTypeId");
	}

	public void setBirthDay(java.util.Date birthDay) {
		set("birthDay", birthDay);
	}

	public java.util.Date getBirthDay() {
		return get("birthDay");
	}

	public void setSex(String sex) {
		set("sex", sex);
	}

	public String getSex() {
		return getStr("sex");
	}

	public void setTel(String tel) {
		set("tel", tel);
	}

	public String getTel() {
		return getStr("tel");
	}

	public void setBeneficiary(String beneficiary) {
		set("beneficiary", beneficiary);
	}

	public String getBeneficiary() {
		return getStr("beneficiary");
	}

	public void setCAt(java.util.Date cAt) {
		set("cAt", cAt);
	}

	public java.util.Date getCAt() {
		return get("cAt");
	}

	public void setIdCard(String idCard) {
		set("idCard", idCard);
	}

	public String getIdCard() {
		return getStr("idCard");
	}

	public void setCardsId(Integer cardsId) {
		set("cardsId", cardsId);
	}

	public Integer getCardsId() {
		return getInt("cardsId");
	}

}
