package com.yhh.whbx.admin.model;


import com.yhh.whbx.admin.model.base.BaseAttachment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Attachment extends BaseAttachment<Attachment> {
	public static final Attachment dao = new Attachment().dao();

	@Override
	public String getTableName() {
		return "s_attachment";
	}
}
