package com.yhh.whbx.admin.model;


import com.yhh.whbx.admin.model.base.BaseAttachment;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Attachment extends BaseAttachment<Attachment> {
	public static final Attachment dao = new Attachment().dao();

	@Override
	public String getTableName() {
		return "s_attachment";
	}

	public List<Attachment> findByObjId(Integer objId){
		return  dao.find("select * from "+getTableName()+" where objId=? and dAt is null",objId);
	}
}
