package com.yhh.whbx.admin.model;

import com.jfinal.plugin.ehcache.CacheKit;
import com.yhh.whbx.Consts;
import com.yhh.whbx.admin.model.base.BaseContent;
import com.yhh.whbx.kits.DateKit;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Content extends BaseContent<Content> {
	public static final Content dao = new Content().dao();

	public String getCAtTxt(){
		return getCAt()==null?"": DateKit.dateToStr(getCAt(),DateKit.STR_DATEFORMATE);
	}

	public String getAuthor(){
		return getUserid()==null?"":User.dao.findById(getUserid()).getNickname();
	}

	public List<Taxonomy> getTaxList(){
		return Taxonomy.dao.findTaxsByCId(getId());
	}

	public String getThumbnailImgUrl(){
		return CacheKit.get(Consts.CACHE_NAMES.paramCache.name(),"qn_url")+getThumbnail();
	}


	@Override
	public boolean equals(Object obj) {
		if (!(obj instanceof Content)) {
			return false;
		}
		Content c = (Content) obj;
		return this.getId().equals(c.getId());
	}

	@Override
	public int hashCode() {
		return getId().hashCode();
	}

}
