package com.yhh.whbx.admin.model;

import com.yhh.whbx.admin.model.base.BaseMapping;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Mapping extends BaseMapping<Mapping> {
	public static final Mapping dao = new Mapping().dao();
}
