package com.yhh.whbx.admin.model;

import com.alibaba.fastjson.JSONArray;
import com.alibaba.fastjson.JSONObject;
import com.xiaoleilu.hutool.log.StaticLog;
import com.yhh.whbx.Consts;
import com.yhh.whbx.admin.model.base.BaseRes;

import java.math.BigInteger;
import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Res extends BaseRes<Res> {
	public static final Res dao = new Res().dao();
	public static String listTree(int id){
		List<Res> resList;
		if(id==0){
			resList = dao.find("select * from s_res   order by seq");
		}else {
			resList = dao.find("select * from s_res where id=? order by seq", id);
		}
		JSONArray ja=new JSONArray();
		JSONObject jo;
		for(Res res:resList){
			jo=new JSONObject();
			jo.put("id",res.getId());
			jo.put("pId",res.getPid());
			jo.put("name",res.getName());
			jo.put("resUrl",res.getUrl());
			jo.put("seq",res.getSeq());
			jo.put("description",res.getDescription());
			jo.put("logged",res.getLogged());
			ja.add(jo);
		}
		StaticLog.info(ja.toJSONString());
		return ja.toJSONString();
	}


	public List<Res> getChildren(){
		List<Res> list=dao.find("select * from s_res where pId=? order by seq",getId());
		return list;
	}

	public List<Res> findResesByUserId(BigInteger userId){
		List<Role> roleList=Role.dao.findRolesByUserId(userId);
		int i=0;
		String p=null;
		for(Role r:roleList){
			if(p==null)
				p=r.getId().toString();
			else
				p=p+","+r.getId().toString();
		}

		List<Res> list= Res.dao.findByCache(Consts.CACHE_NAMES.userReses.name(),userId,"select r.* from s_res r left join s_role_res rr on r.id=rr.resId  where rr.roleId in (?) and r.pid=0 order by r.seq",p);
		return list;
	}

	public List<Res> findSecResesByUserId(BigInteger userId,long rId){

		List<Role> roleList=Role.dao.findRolesByUserId(userId);
		int i=0;
		String p=null;
		for(Role r:roleList){
			if(p==null)
				p=r.getId().toString();
			else
				p=p+","+r.getId().toString();
		}

		List<Res> list= Res.dao.findByCache(Consts.CACHE_NAMES.userReses.name(),userId+""+rId,"select r.* from s_res r left join s_role_res rr on r.id=rr.resId  where rr.roleId in (?) and r.pid=? order by r.seq",p,rId);
		return list;
	}
}
