package com.yhh.whbx.admin.model;

import com.jfinal.plugin.activerecord.Db;
import com.yhh.whbx.admin.model.base.BaseTaxonomy;

import java.util.ArrayList;
import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Taxonomy extends BaseTaxonomy<Taxonomy> {

	public static final Taxonomy dao = new Taxonomy().dao();

	private List<Taxonomy> children =new ArrayList<>();

	public List<Taxonomy> getChildren() {
		return children;
	}

	public void setChildren(List<Taxonomy> children) {
		this.children = children;
	}

	public List<Taxonomy> findAllList(){
		List<Taxonomy> list=dao.find("select * from s_taxonomy where parentId =0 and dAt is null ");
		for (Taxonomy taxonomy:list){
			findChildren(taxonomy);
		}
		return list;
	}

	public List<Taxonomy> findAllListByModule(String module){
		List<Taxonomy> list=dao.find("select * from s_taxonomy where parentId =0 and dAt is null and module=?",module);
		for (Taxonomy taxonomy:list){
			findChildren(taxonomy);
		}
		return list;
	}

	private void findChildren(Taxonomy taxonomy){
		List<Taxonomy> list=dao.find("select * from s_taxonomy where parentId =? and dAt is null ",taxonomy.getId());
		for (Taxonomy t:list){
			findChildren(t);
		}
		taxonomy.getChildren().addAll(list);

	}

	public List<Taxonomy> findByModuleExcept(String m){
		return dao.find("select * from s_taxonomy where module=? and parentId is null and dAt is null ",m);
	}


	public void updateChildrenModule(Long pId,String module){
		Db.update("update  s_taxonomy set module=? where parentId=? and dAt is null",module,pId);
	}


	public List findByTitleAndPId(String title,Long pId){
		return dao.find("select * from s_taxonomy where title=? and dAt is null and parentId=?",title,pId);
	}

	public List findByTitleAndPIdAndNEId(String title,Long pId,Long id){
		return dao.find("select * from s_taxonomy where title=? and dAt is null and parentId=? and id<>?",title,pId,id);
	}

	public boolean getExpand(){
		return children.size()>0?true:false;
	}
}
