package com.yhh.whbx.admin.model;

import com.yhh.whbx.admin.model.base.BaseTaxonomy;

import java.util.ArrayList;
import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Taxonomy extends BaseTaxonomy<Taxonomy> {

	public static final Taxonomy dao = new Taxonomy().dao();

	private List<Taxonomy> children =new ArrayList<>();

	public List<Taxonomy> getChildren() {
		return children;
	}

	public void setChildren(List<Taxonomy> children) {
		this.children = children;
	}

	public List<Taxonomy> findAllList(){
		List<Taxonomy> list=dao.find("select * from s_taxonomy where parent_id is null and d_at is null ");
		for (Taxonomy taxonomy:list){
			findChildren(taxonomy);
		}
		return list;
	}

	private void findChildren(Taxonomy taxonomy){
		List<Taxonomy> list=dao.find("select * from s_taxonomy where parent_id =? and d_at is null ",taxonomy.getId());
		for (Taxonomy t:list){
			findChildren(t);
		}
		taxonomy.getChildren().addAll(list);

	}

	public List<Taxonomy> findByModuleExcept(String m){
		return dao.find("select * from s_taxonomy where module=? and parent_id is null and d_at is null ",m);
	}


}
