package com.yhh.whbx.card.model;


import com.yhh.whbx.card.model.base.BaseCardsIp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CardsIp extends BaseCardsIp<CardsIp> {
	public static final CardsIp dao = new CardsIp().dao();

	@Override
	public String getTableName() {
		return "b_cards_ip";
	}
}
