package com.yhh.whbx.card.model;


import com.jfinal.plugin.ehcache.CacheKit;
import com.xiaoleilu.hutool.util.StrUtil;
import com.yhh.whbx.Consts;
import com.yhh.whbx.admin.model.Taxonomy;
import com.yhh.whbx.card.model.base.BaseCardapply;
import com.yhh.whbx.kits.DateKit;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Cardapply extends BaseCardapply<Cardapply> {
	public static final Cardapply dao = new Cardapply().dao();

	@Override
	public String getTableName() {
		return "b_cardapply";
	}

	public List<Cardapply> findAllNotDel(){
		return dao.find("select * from "+getTableName()+" where dAt is null");
	}

	public List<Cardapply> findByBatchAndCardtype(Integer ct,String batch){
		return dao.find("select * from "+getTableName()+" where batch=? and cardtypeId=?",batch,ct);
	}

	public List<Cardapply> findByBatchAndCardtypeAndNEId(Integer ct,String batch,Long id){
		return dao.find("select * from "+getTableName()+" where batch=? and cardtypeId=? and id <>?",batch,ct,id);
	}

	public String getCardtypeTxt(){
		return Cardtype.dao.findById(getCardtypeId()).getName();
	}

	public String getMediaTxt(){
		Taxonomy taxonomy=null;
		if(getMedia()!=null)
		 taxonomy=(Taxonomy)CacheKit.get(Consts.CACHE_NAMES.taxonomy.name(),getMedia().toString());
		return getMedia()==null?"":taxonomy!=null?taxonomy.getTitle():"";
	}

	public String getCAtTxt(){
		return getCAt()==null?"": DateKit.dateToStr(getCAt(),DateKit.STR_DATEFORMATE);
	}
}
