package com.yhh.whbx.card.model;


import com.yhh.whbx.card.model.base.BaseCardsCarIp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CardsCarIp extends BaseCardsCarIp<CardsCarIp> {
	public static final CardsCarIp dao = new CardsCarIp().dao();

	@Override
	public String getTableName() {
		return "b_cards_car_ip";
	}
}
