package com.yhh.whbx.card.model;


import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Record;
import com.yhh.whbx.card.model.base.BaseCards;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Cards extends BaseCards<Cards> {
	public static final Cards dao = new Cards().dao();

	@Override
	public String getTableName() {
		return "b_cards";
	}

	public Long countByCardapplyId(Integer applyId){
		Record record=Db.findFirst("select count(*) as num from "+getTableName()+" where applyId=?",applyId);
		return record.getLong("num");
	}

	public List<Cards> findByCardapplyId(Integer applyId){
		return dao.find("select *  from "+getTableName()+" where applyId=?",applyId);
	}

	public void updateStatusByCardapplyId(Integer applyId){
		Db.batchUpdate(findByCardapplyId(applyId),50);
	}
}
