package com.yhh.whbx.card.model;

import com.yhh.whbx.card.model.base.BaseCardtype;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Cardtype extends BaseCardtype<Cardtype> {
	public static final Cardtype dao = new Cardtype().dao();

	@Override
	public String getTableName() {
		return "b_cardType";
	}
}
