package com.yhh.whbx.card.model;


import com.yhh.whbx.card.model.base.BaseCardsCarPh;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CardsCarPh extends BaseCardsCarPh<CardsCarPh> {
	public static final CardsCarPh dao = new CardsCarPh().dao();

	@Override
	public String getTableName() {
		return "b_cards_car_ph";
	}


}
