package com.yhh.whbx.card.model;


import com.yhh.whbx.card.model.base.BaseCardapply;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Cardapply extends BaseCardapply<Cardapply> {
	public static final Cardapply dao = new Cardapply().dao();

	@Override
	public String getTableName() {
		return "b_cardapply";
	}

	public List<Cardapply> findAllNotDel(){
		return dao.find("select * from "+getTableName()+" where dAt is null");
	}

	public List<Cardapply> findByBatchAndCardtype(Integer ct,String batch){
		return dao.find("select * from "+getTableName()+" where batch=? and cardtypeId=?",batch,ct);
	}

	public List<Cardapply> findByBatchAndCardtypeAndNEId(Integer ct,String batch,Long id){
		return dao.find("select * from "+getTableName()+" where batch=? and cardtypeId=? and id <>?",batch,ct,id);
	}
}
