package com.yhh.whbx.card.model;


import com.yhh.whbx.Consts;
import com.yhh.whbx.admin.model.User;
import com.yhh.whbx.card.model.base.BaseDepot;
import com.yhh.whbx.sale.model.Salesmen;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Depot extends BaseDepot<Depot> {
	public static final Depot dao = new Depot().dao();

	@Override
	public String getTableName() {
		return "b_depot";
	}

	public List<Depot> findByCodeAndNeId(String code, Long id){
		return dao.find("select * from "+getTableName()+" where code =? and id<>?",code,id);
	}


	public String getCardtypeTxt(){

		Cardtype cardtype=Cardtype.dao.findById(getCardtypeId());
		return cardtype!=null?cardtype.getName():"";
	}

	public String getBatch(){
		Cardapply cardapply=Cardapply.dao.findById(getCardapplyId());
		return cardapply==null?"":cardapply.getBatch();
	}

	public String getSalesmenTxt(){
		return getSalesmenId()!=null?Salesmen.dao.findById(getSalesmenId()).getName():"无";
	}

	public String getStatusTxt(){
		return getStatus().equals(Consts.STATUS.forbidden.getVal())? Consts.STATUS.forbidden.getValTxt(): Consts.STATUS.enable.getValTxt();
	}

	public String getOutstatusTxt(){
		return getOutStatus().equals(Consts.YORN_STR.no.getVal())? Consts.YORN_STR.no.getLabel(): Consts.YORN_STR.yes.getLabel();
	}

	public String getOperTxt(){
		return getOper()!=null? User.dao.findById(getOper()).getNickname():"无";
	}

	public String getAllLockStatus(){
		int unlockCount=Cards.dao.countUnlockByDepotId(getId().intValue());
		int count=getENum()-getBNum()+1;
		return unlockCount==count? Consts.YORN_STR.yes.getVal(): Consts.YORN_STR.no.getVal();
	}


}
