package com.yhh.whbx.card.model;


import com.yhh.whbx.card.model.base.BaseInsuranceOcc;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class InsuranceOcc extends BaseInsuranceOcc<InsuranceOcc> {
	public static final InsuranceOcc dao = new InsuranceOcc().dao();

	public List<InsuranceOcc> findFirstLevel(String insurance){
		String sql="select * from b_insurance_occ where pCode is null and insurance=?";
		return dao.find(sql,insurance);
	}

	public List<InsuranceOcc> findSecLevel(String pCode,String insurance){
		String sql="select * from b_insurance_occ where pCode =? and insurance=? and type is null";
		return dao.find(sql,pCode,insurance);
	}

	public List<InsuranceOcc> findThirdLevel(String pCode,String insurance){
		String sql="select * from b_insurance_occ where pCode =? and insurance=? and type is not null";
		return dao.find(sql,pCode,insurance);
	}

}
