package com.yhh.whbx.card.model;


import com.yhh.whbx.Consts;
import com.yhh.whbx.card.model.base.BaseUnlock;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Unlock extends BaseUnlock<Unlock> {
	public static final Unlock dao = new Unlock().dao();

	@Override
	public String getTableName() {
		return "b_unlock";
	}

	public String  checkNumEnable(Integer bNum,Integer eNum,Integer depotId){
		String sql="select * from "+getTableName()+" where ((? between bNum and eNum) or (? between bNum and eNum ) or (? <bNum and ? >eNum ) ) and depotId=?";
		List<Unlock> list=Unlock.dao.find(sql,bNum,eNum,bNum,eNum,depotId);
		return !list.isEmpty()? Consts.YORN_STR.no.getVal(): Consts.YORN_STR.yes.getVal();
	}
}
