package com.yhh.whbx.card.model;


import com.yhh.whbx.card.model.base.BaseUnlock;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Unlock extends BaseUnlock<Unlock> {
	public static final Unlock dao = new Unlock().dao();

	@Override
	public String getTableName() {
		return "b_unlock";
	}
}
