package com.yhh.whbx.admin.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.yhh.whbx.core.CoreModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRes<M extends BaseRes<M>> extends CoreModel<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}
	
	public Long getId() {
		return getLong("id");
	}

	public void setName(String name) {
		set("name", name);
	}
	
	public String getName() {
		return getStr("name");
	}

	public void setUrl(String url) {
		set("url", url);
	}
	
	public String getUrl() {
		return getStr("url");
	}

	public void setDescription(String description) {
		set("description", description);
	}
	
	public String getDescription() {
		return getStr("description");
	}

	public void setPid(Integer pid) {
		set("pid", pid);
	}
	
	public Integer getPid() {
		return getInt("pid");
	}

	public void setSeq(Integer seq) {
		set("seq", seq);
	}
	
	public Integer getSeq() {
		return getInt("seq");
	}

	public void setLogged(String logged) {
		set("logged", logged);
	}
	
	public String getLogged() {
		return getStr("logged");
	}

	public void setType(String type) {
		set("type", type);
	}
	
	public String getType() {
		return getStr("type");
	}

	public void setEnabled(String enabled) {
		set("enabled", enabled);
	}
	
	public String getEnabled() {
		return getStr("enabled");
	}

}
