package com.yhh.whbx.admin.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.yhh.whbx.core.CoreModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseContent<M extends BaseContent<M>> extends CoreModel<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return getLong("id");
	}

	public void setTitle(String title) {
		set("title", title);
	}

	public String getTitle() {
		return getStr("title");
	}

	public void setText(String text) {
		set("text", text);
	}

	public String getText() {
		return getStr("text");
	}

	public void setSummary(String summary) {
		set("summary", summary);
	}

	public String getSummary() {
		return getStr("summary");
	}

	public void setLinkTo(String linkTo) {
		set("link_to", linkTo);
	}

	public String getLinkTo() {
		return getStr("link_to");
	}

	public void setMarkdownEnable(Boolean markdownEnable) {
		set("markdown_enable", markdownEnable);
	}

	public Boolean getMarkdownEnable() {
		return get("markdown_enable");
	}

	public void setThumbnail(String thumbnail) {
		set("thumbnail", thumbnail);
	}

	public String getThumbnail() {
		return getStr("thumbnail");
	}

	public void setModule(String module) {
		set("module", module);
	}

	public String getModule() {
		return getStr("module");
	}

	public void setUserId(java.math.BigInteger userId) {
		set("user_id", userId);
	}

	public java.math.BigInteger getUserId() {
		return get("user_id");
	}

	public void setUserIp(String userIp) {
		set("user_ip", userIp);
	}

	public String getUserIp() {
		return getStr("user_ip");
	}

	public void setUserAgent(String userAgent) {
		set("user_agent", userAgent);
	}

	public String getUserAgent() {
		return getStr("user_agent");
	}

	public void setParentId(Long parentId) {
		set("parent_id", parentId);
	}

	public Long getParentId() {
		return getLong("parent_id");
	}

	public void setStatus(String status) {
		set("status", status);
	}

	public String getStatus() {
		return getStr("status");
	}

	public void setVoteUp(Long voteUp) {
		set("vote_up", voteUp);
	}

	public Long getVoteUp() {
		return getLong("vote_up");
	}

	public void setVoteDown(Long voteDown) {
		set("vote_down", voteDown);
	}

	public Long getVoteDown() {
		return getLong("vote_down");
	}

	public void setRate(Integer rate) {
		set("rate", rate);
	}

	public Integer getRate() {
		return getInt("rate");
	}

	public void setRateCount(Long rateCount) {
		set("rate_count", rateCount);
	}

	public Long getRateCount() {
		return getLong("rate_count");
	}

	public void setCommentStatus(String commentStatus) {
		set("comment_status", commentStatus);
	}

	public String getCommentStatus() {
		return getStr("comment_status");
	}

	public void setCommentCount(Long commentCount) {
		set("comment_count", commentCount);
	}

	public Long getCommentCount() {
		return getLong("comment_count");
	}

	public void setCommentTime(java.util.Date commentTime) {
		set("comment_time", commentTime);
	}

	public java.util.Date getCommentTime() {
		return get("comment_time");
	}

	public void setViewCount(Long viewCount) {
		set("view_count", viewCount);
	}

	public Long getViewCount() {
		return getLong("view_count");
	}

	public void setCAt(java.util.Date cAt) {
		set("c_at", cAt);
	}

	public java.util.Date getCAt() {
		return get("c_at");
	}

	public void setDAt(java.util.Date dAt) {
		set("d_at", dAt);
	}

	public java.util.Date getDAt() {
		return get("d_at");
	}

	public void setMAt(java.util.Date mAt) {
		set("m_at", mAt);
	}

	public java.util.Date getMAt() {
		return get("m_at");
	}

	public void setMetaKeywords(String metaKeywords) {
		set("meta_keywords", metaKeywords);
	}

	public String getMetaKeywords() {
		return getStr("meta_keywords");
	}

	public void setMetaDescription(String metaDescription) {
		set("meta_description", metaDescription);
	}

	public String getMetaDescription() {
		return getStr("meta_description");
	}

	public void setRemarks(String remarks) {
		set("remarks", remarks);
	}

	public String getRemarks() {
		return getStr("remarks");
	}

	public void setGood(Boolean good) {
		set("good", good);
	}

	public Boolean getGood() {
		return get("good");
	}

	public void setTop(Boolean top) {
		set("top", top);
	}

	public Boolean getTop() {
		return get("top");
	}

	public void setFlag(String flag) {
		set("flag", flag);
	}

	public String getFlag() {
		return getStr("flag");
	}

	public void setCollectCount(Integer collectCount) {
		set("collect_count", collectCount);
	}

	public Integer getCollectCount() {
		return getInt("collect_count");
	}

	public void setLaudCount(Integer laudCount) {
		set("laud_count", laudCount);
	}

	public Integer getLaudCount() {
		return getInt("laud_count");
	}

}
