package com.yhh.whbx.admin.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;
import com.yhh.whbx.core.CoreModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTaxonomy<M extends BaseTaxonomy<M>> extends CoreModel<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return getLong("id");
	}

	public void setTitle(String title) {
		set("title", title);
	}

	public String getTitle() {
		return getStr("title");
	}

	public void setText(String text) {
		set("text", text);
	}

	public String getText() {
		return getStr("text");
	}

	public void setModule(String module) {
		set("module", module);
	}

	public String getModule() {
		return getStr("module");
	}

	public void setCount(Long count) {
		set("count", count);
	}

	public Long getCount() {
		return getLong("count");
	}

	public void setOrder(Integer order) {
		set("order", order);
	}

	public Integer getOrder() {
		return getInt("order");
	}

	public void setParentId(Long parentId) {
		set("parentId", parentId);
	}

	public Long getParentId() {
		return getLong("parentId");
	}

	public void setCAt(java.util.Date cAt) {
		set("cAt", cAt);
	}

	public java.util.Date getCAt() {
		return get("cAt");
	}

	public void setDAt(java.util.Date dAt) {
		set("dAt", dAt);
	}

	public java.util.Date getDAt() {
		return get("dAt");
	}

}
