package com.yhh.whbx.admin.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseContent<M extends BaseContent<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return getLong("id");
	}

	public void setTitle(String title) {
		set("title", title);
	}

	public String getTitle() {
		return getStr("title");
	}

	public void setText(String text) {
		set("text", text);
	}

	public String getText() {
		return getStr("text");
	}

	public void setSummary(String summary) {
		set("summary", summary);
	}

	public String getSummary() {
		return getStr("summary");
	}

	public void setLinkTo(String linkTo) {
		set("linkTo", linkTo);
	}

	public String getLinkTo() {
		return getStr("linkTo");
	}

	public void setThumbnail(String thumbnail) {
		set("thumbnail", thumbnail);
	}

	public String getThumbnail() {
		return getStr("thumbnail");
	}

	public void setModule(String module) {
		set("module", module);
	}

	public String getModule() {
		return getStr("module");
	}

	public void setUserid(java.math.BigInteger userid) {
		set("userid", userid);
	}

	public java.math.BigInteger getUserid() {
		return get("userid");
	}

	public void setUserip(String userip) {
		set("userip", userip);
	}

	public String getUserip() {
		return getStr("userip");
	}

	public void setUserAgent(String userAgent) {
		set("userAgent", userAgent);
	}

	public String getUserAgent() {
		return getStr("userAgent");
	}

	public void setParentId(Long parentId) {
		set("parentId", parentId);
	}

	public Long getParentId() {
		return getLong("parentId");
	}

	public void setStatus(String status) {
		set("status", status);
	}

	public String getStatus() {
		return getStr("status");
	}

	public void setVoteUp(Long voteUp) {
		set("voteUp", voteUp);
	}

	public Long getVoteUp() {
		return getLong("voteUp");
	}

	public void setVoteDown(Long voteDown) {
		set("voteDown", voteDown);
	}

	public Long getVoteDown() {
		return getLong("voteDown");
	}

	public void setRate(Integer rate) {
		set("rate", rate);
	}

	public Integer getRate() {
		return getInt("rate");
	}

	public void setRatecount(Long ratecount) {
		set("ratecount", ratecount);
	}

	public Long getRatecount() {
		return getLong("ratecount");
	}

	public void setCommentStatus(String commentStatus) {
		set("commentStatus", commentStatus);
	}

	public String getCommentStatus() {
		return getStr("commentStatus");
	}

	public void setCommentCount(Long commentCount) {
		set("commentCount", commentCount);
	}

	public Long getCommentCount() {
		return getLong("commentCount");
	}

	public void setCommentTime(java.util.Date commentTime) {
		set("commentTime", commentTime);
	}

	public java.util.Date getCommentTime() {
		return get("commentTime");
	}

	public void setViewCount(Long viewCount) {
		set("viewCount", viewCount);
	}

	public Long getViewCount() {
		return getLong("viewCount");
	}

	public void setCAt(java.util.Date cAt) {
		set("cAt", cAt);
	}

	public java.util.Date getCAt() {
		return get("cAt");
	}

	public void setDAt(java.util.Date dAt) {
		set("dAt", dAt);
	}

	public java.util.Date getDAt() {
		return get("dAt");
	}

	public void setMAt(java.util.Date mAt) {
		set("mAt", mAt);
	}

	public java.util.Date getMAt() {
		return get("mAt");
	}

	public void setMetaKeywords(String metaKeywords) {
		set("metaKeywords", metaKeywords);
	}

	public String getMetaKeywords() {
		return getStr("metaKeywords");
	}

	public void setMetaDesc(String metaDesc) {
		set("metaDesc", metaDesc);
	}

	public String getMetaDesc() {
		return getStr("metaDesc");
	}

	public void setRemarks(String remarks) {
		set("remarks", remarks);
	}

	public String getRemarks() {
		return getStr("remarks");
	}

	public void setGood(Boolean good) {
		set("good", good);
	}

	public Boolean getGood() {
		return get("good");
	}

	public void setTop(Boolean top) {
		set("top", top);
	}

	public Boolean getTop() {
		return get("top");
	}

	public void setFlag(String flag) {
		set("flag", flag);
	}

	public String getFlag() {
		return getStr("flag");
	}

	public void setCollectCount(Integer collectCount) {
		set("collectCount", collectCount);
	}

	public Integer getCollectCount() {
		return getInt("collectCount");
	}

	public void setLaudCount(Integer laudCount) {
		set("laudCount", laudCount);
	}

	public Integer getLaudCount() {
		return getInt("laudCount");
	}

}
