package com.yhh.whbx.admin.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.yhh.whbx.core.CoreModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTaxonomy<M extends BaseTaxonomy<M>> extends CoreModel<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return getLong("id");
	}

	public void setTitle(String title) {
		set("title", title);
	}

	public String getTitle() {
		return getStr("title");
	}

	public void setText(String text) {
		set("text", text);
	}

	public String getText() {
		return getStr("text");
	}

	public void setContentModule(String contentModule) {
		set("content_module", contentModule);
	}

	public String getContentModule() {
		return getStr("content_module");
	}

	public void setContentCount(Long contentCount) {
		set("content_count", contentCount);
	}

	public Long getContentCount() {
		return getLong("content_count");
	}

	public void setOrderNumber(Integer orderNumber) {
		set("order_number", orderNumber);
	}

	public Integer getOrderNumber() {
		return getInt("order_number");
	}

	public void setParentId(Long parentId) {
		set("parent_id", parentId);
	}

	public Long getParentId() {
		return getLong("parent_id");
	}

	public void setCAt(java.util.Date cAt) {
		set("c_at", cAt);
	}

	public java.util.Date getCAt() {
		return get("c_at");
	}

	public void setDAt(java.util.Date dAt) {
		set("d_at", dAt);
	}

	public java.util.Date getDAt() {
		return get("d_at");
	}

}
