package com.yhh.whbx.core;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;
import com.yhh.whbx.admin.model.*;
import com.yhh.whbx.card.model.*;
import com.yhh.whbx.sale.model.Salesmen;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
//		arp.addMapping("ump_order", "id", Order.class);
		arp.addMapping("s_param", Param.class);
		arp.addMapping("s_res", Res.class);
		arp.addMapping("s_role", Role.class);
		arp.addMapping("s_role_res", RoleRes.class);
		arp.addMapping("s_user", User.class);
		arp.addMapping("s_user_role", UserRole.class);
		arp.addMapping("s_content", Content.class);
		arp.addMapping("s_mapping", Mapping.class);
		arp.addMapping("s_taxonomy", Taxonomy.class);
		arp.addMapping("b_salesmen", Salesmen.class);
		arp.addMapping("b_cardType", Cardtype.class);
		arp.addMapping("s_attachment", Attachment.class);
		arp.addMapping("b_cards", Cards.class);
		arp.addMapping("b_cardapply", Cardapply.class);
		arp.addMapping("b_depot", Depot.class);
		arp.addMapping("b_unlock", Unlock.class);
		arp.addMapping("b_insurance_occ", InsuranceOcc.class);
		arp.addMapping("b_cards_ph", CardsPh.class);
		arp.addMapping("b_cards_ip", CardsIp.class);
		arp.addMapping("b_cards_car_ip", CardsCarIp.class);
		arp.addMapping("b_cards_car_ph", CardsCarPh.class);

	}
}

