package com.yhh.whbx.sale.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;
import com.yhh.whbx.core.CoreModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSalesmen<M extends BaseSalesmen<M>> extends CoreModel<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return getLong("id");
	}

	public void setCode(String code) {
		set("code", code);
	}

	public String getCode() {
		return getStr("code");
	}

	public void setName(String name) {
		set("name", name);
	}

	public String getName() {
		return getStr("name");
	}

	public void setIdcard(String idcard) {
		set("idcard", idcard);
	}

	public String getIdcard() {
		return getStr("idcard");
	}

	public void setPhone(String phone) {
		set("phone", phone);
	}

	public String getPhone() {
		return getStr("phone");
	}

	public void setBankcard(String bankcard) {
		set("bankcard", bankcard);
	}

	public String getBankcard() {
		return getStr("bankcard");
	}

	public void setAddress(String address) {
		set("address", address);
	}

	public String getAddress() {
		return getStr("address");
	}

	public void setEmail(String email) {
		set("email", email);
	}

	public String getEmail() {
		return getStr("email");
	}

	public void setType(Integer type) {
		set("type", type);
	}

	public Integer getType() {
		return getInt("type");
	}

	public void setLevel(Integer level) {
		set("level", level);
	}

	public Integer getLevel() {
		return getInt("level");
	}

	public void setStatus(String status) {
		set("status", status);
	}

	public String getStatus() {
		return getStr("status");
	}

	public void setCAt(java.util.Date cAt) {
		set("cAt", cAt);
	}

	public java.util.Date getCAt() {
		return get("cAt");
	}

	public void setDAt(java.util.Date dAt) {
		set("dAt", dAt);
	}

	public java.util.Date getDAt() {
		return get("dAt");
	}

	public void setOper(Integer oper) {
		set("oper", oper);
	}

	public Integer getOper() {
		return getInt("oper");
	}

	public void setPId(Integer pId) {
		set("pId", pId);
	}

	public Integer getPId() {
		return getInt("pId");
	}

}
