#namespace("salesmen")
  #include("salesmen.sql")
#end
#namespace("cardType")
  #include("cardType.sql")
#end
#namespace("cardapply")
  #include("cardapply.sql")
#end
#namespace("depot")
  #include("depot.sql")
#end
#namespace("cards")
  #include("cards.sql")
#end
#namespace("cardsIp")
  #include("cardsIp.sql")
#end