package com.yhh.whbx.sale.model;


import com.jfinal.plugin.ehcache.CacheKit;
import com.yhh.whbx.Consts;
import com.yhh.whbx.admin.model.Taxonomy;
import com.yhh.whbx.kits.DateKit;
import com.yhh.whbx.sale.model.base.BaseSalesmen;
import net.sf.ehcache.store.CacheKeySet;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Salesmen extends BaseSalesmen<Salesmen> {
	public static final Salesmen dao = new Salesmen().dao();

	public List findByCode(String code){
		String sql="select * from b_salesmen where dAt is null and code=? ";
		return dao.find(sql,code);
	}

	public List findByEmail(String email){
		String sql="select * from b_salesmen where dAt is null and email=? ";
		return dao.find(sql,email);
	}

	public List findByIdcard(String idcard){
		String sql="select * from b_salesmen where dAt is null and idcard=? ";
		return dao.find(sql,idcard);
	}

	public List findByPhone(String phone){
		String sql="select * from b_salesmen where dAt is null and phone=? ";
		return dao.find(sql,phone);
	}

	public List findByNameLike(String name){
		String sql="select * from b_salesmen where dAt is null and name like ?";
		return dao.find(sql,name);
	}


	public List findAll(){
		return dao.find("select * from b_salesmen where dAt is null ");
	}

	public String getTypeTxt(){
		Taxonomy taxonomy= (Taxonomy)CacheKit.get(Consts.CACHE_NAMES.taxonomy.name(),getType().toString());
		return taxonomy.getTitle();
	}

	public String getLevelTxt(){
		Taxonomy taxonomy= (Taxonomy)CacheKit.get(Consts.CACHE_NAMES.taxonomy.name(),getLevel().toString());
		return taxonomy.getTitle();
	}

	public String getStatusTxt(){
		return getStatus().equals(Consts.STATUS.enable.getVal())? Consts.STATUS.enable.getValTxt(): Consts.STATUS.forbidden.getValTxt();
	}

	public String getCAtTxt(){
		return DateKit.dateToStr(getCAt(),DateKit.STR_DATEFORMATE);
	}

	public String getParentName(){
		String pname=null;
		if(getPId()!=null){
			Salesmen salesmen=Salesmen.dao.findById(getPId());
			pname=salesmen.getName();
		}
		return pname;
	}

	@Override
	public String getTableName() {
		return "b_salesmen";
	}
}
